### ISSUE TITLE
Scope override in Logic

### ISSUE THREAD

**Issue by erf** [letsar/binder#10]
Quick question: There is no way to avoid the repetitive `scope` override in `Logic` without making it a class?

**Comment by letsar** [comment]
No, I wanted to use a mixin and not a class so that your logic business can extend something else.

But I created some snippets for vscode to aleviate the dev to write it everytime.
You can download them here: https://marketplace.visualstudio.com/items?itemName=romain-rastel.flutter-binder-snippets
Then you can use the `lref ` snippet to create the reference and the logic class boilerplate.

**Comment by erf** [comment]
Cool, thanks
